spring:
  application:
    name: SpringAI
  ai:
    openai:
      api-key: wilfredkey
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      chat:
        model: llama3.2

server:
  port: 8999



